spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_test_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  liquibase:
    enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/inventory-saas
